### ISSUE TITLE
Error when starting a newly created app.

### ISSUE THREAD

**Issue by Anshr** [Azure-Samples/cra-template-iot-cardboard-js#10]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> populated .env file with required data, `npm start`. Node version is `17.9.1`

### Any log messages given by the failure
> Uncaught TypeError: util__WEBPACK_IMPORTED_MODULE_0__.TextEncoder is not a constructor
    at ./node_modules/@microsoft/iot-cardboard-js/internal/axios-1bc8e67b.js (bundle.js:675181:21)
    at options.factory (bundle.js:803898:31)
    at __webpack_require__ (bundle.js:803291:33)
    at fn (bundle.js:803555:21)
    at ./node_modules/@microsoft/iot-cardboard-js/internal/SceneView-3eed0d73.js (bundle.js:625275:76)
    at options.factory (bundle.js:803898:31)
    at __webpack_require__ (bundle.js:803291:33)
    at fn (bundle.js:803555:21)
    at ./node_modules/@microsoft/iot-cardboard-js/internal/ADT3DGlobe-82f8ed87.js (bundle.js:25036:80)
    at options.factory (bundle.js:803898:31)

### Expected/desired behavior
> Expected app to start. 

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
macOs Monterey
### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Anshr** [comment]
Re-created the app with `16.20.0` node version.
